name: asgard_http_interceptor
description: Fork of http_interceptor with attachment support.
version: 1.0.2
homepage: https://github.com/sunnykinger/http_interceptor
repository: https://github.com/sunnykinger/http_interceptor

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  test: ^1.17.5
  effective_dart: ^1.3.2